- name: Install required packages
  apt:
    name: "{{ package }}"
    state: present
    update_cache: yes

- name: Checking Domain Join status
  command: id "{{ joinUser }}"
  register: ad_status
  changed_when: false
  ignore_errors: true

- name: Domain configs and Join {{ domainName }}
  block:
    - name: Join Ubuntu  into Domain {{ domainName }}
      expect:
        command: /bin/bash -c "/usr/sbin/realm join -U {{ joinUser }} {{ domainName }}"
        responses:
          Password for *: "{{ joinUserPass }}"

    - name: Allow user Login without FQDN
      lineinfile:
        backup: yes
        state: present
        dest: /etc/sssd/sssd.conf
        regexp: '^{{ item.search }}'
        line: '{{ item.replace }}'
      with_items:
        - { search: 'use_fully_qualified_names', replace: 'use_fully_qualified_names = False' }
        - { search: 'fallback_homedir', replace: 'fallback_homedir = /home/%u'}
        - { search: 'access_provider', replace: 'access_provider = simple'}
      notify: restart sssd

    - name: Add pam authentification to common-session
      lineinfile:
        path: "/etc/pam.d/common-session"
        line: "session required        pam_mkhomedir.so skel=/etc/skel umask=077"

    - name: deny all domain users
      command: /bin/bash -c "realm deny –all"
    
    - name:  permit specified group
      command: /bin/bash -c "realm permit -g '{{ domainGroupName }}'"

    - name: Copy sudoers
      ansible.builtin.template:
        src: domain_admins.j2
        dest: /etc/sudoers.d/admins       
  when: ad_status.rc !=0

